# Generated by Django 4.1.7 on 2023-03-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webnews", "0002_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
